services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --hostname=localhost
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: user
      DB_PASSWORD: secret
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/realms/default-realm.json
    ports:
      - "8090:8080"

  smtp:
    image: mailhog/mailhog
    container_name: smtp
    ports:
      - "1025:1025"
      - "8025:8025"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: local-sql
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d