services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --hostname=localhost
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: local-sql
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/realms/default-realm.json
    ports:
      - "8090:8080"
  smtp:
    image: mailhog/mailhog
    container_name: smtp
    ports:
      - "1025:1025"
      - "8025:8025"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: local-sql
      MYSQL_DATABASE: keycloak
    ports:
      - "3306:3306"

  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3308:3306'
