#Dont forget to build maven firstly.
services:
  backend:
    build: .
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_APPLICATION_BASE_URL=localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3308/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_MAIL_HOST=localhost
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=todo
      - SPRING_MAIL_PASSWORD=todo
      - KEYCLOAK_RESOURCE=todo
    network_mode: host
    restart: always
  mysql:
    container_name: 'mysql'
    image: 'mysql:8.0.33'
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - 3308:3306
