services:
  backend:
    image: ghcr.io/scouts-gidsen-lebbeke/backend:dev
    container_name: backend
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    network_mode: host
    restart: always
    volumes:
      - ./images:/images:rw,z
      - ./logs:/logs:rw,z