version: '3.8'

services:
  backend:
    image: ghcr.io/scouts-gidsen-lebbeke/backend:dev
    container_name: backend
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    network_mode: host
    restart: always
    volumes:
      - ./images:/images:rw,z