spring:
  application:
    environment: local
  datasource:
    url: jdbc:mariadb://localhost:3308/application
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: localhost
    port: 1025
    alert:
      enabled: false
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

# unstable and on demand
#rest:
#  ga:
#    url: https://ga-staging.scoutsengidsenvlaanderen.be/groepsadmin/rest-ga

keycloak:
  resource: master-realm
  realm: master
  auth-server-url: http://localhost:8090/

logging:
  level:
    root: INFO
    be.sgl.backend: TRACE

organization:
  api-key:
    mollie: "invalid-key"