spring:
  application:
    environment: dev
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    alert:
      enabled: false

# unstable and on demand
#rest:
#  ga:
#    url: https://ga-staging.scoutsengidsenvlaanderen.be/groepsadmin/rest-ga

logging:
  level:
    be.slg.backend: DEBUG