package be.sgl.backend.service.membership

import be.sgl.backend.entity.membership.MembershipPeriod
import be.sgl.backend.entity.user.User
import be.sgl.backend.repository.membership.MembershipPeriodRepository
import be.sgl.backend.repository.membership.MembershipRepository
import be.sgl.backend.service.MailService
import be.sgl.backend.util.I18nUtil
import be.sgl.backend.util.Usecase
import mu.KotlinLogging
import org.springframework.scheduling.annotation.Scheduled
import java.time.LocalDate

@Usecase
class NotifyMembersOfNewMembershipPeriod(
    private val membershipRepository: MembershipRepository,
    private val membershipPeriodRepository: MembershipPeriodRepository,
    private val mailService: MailService,
    private val generateNewMembershipPeriod: GenerateNewMembershipPeriod
) {

    private val logger = KotlinLogging.logger {}

    @Scheduled(cron = "0 0 1 * * ?")
    fun execute() {
        logger.info { "Checking if yesterdays active membership period ended, denoting a new active period..." }
        val yesterday = LocalDate.now().minusDays(1)
        val yesterdaysActivePeriod = membershipPeriodRepository.getPeriodActiveOn(yesterday)
        if (yesterdaysActivePeriod.end.isAfter(LocalDate.now())) {
            logger.info { "Yesterdays active period did not end by today, no notification needed." }
            return
        }
        var currentActivePeriod = membershipPeriodRepository.findActivePeriod()
        if (currentActivePeriod == null) {
            logger.warn { "No current active period found, one will be autogenerated!" }
            currentActivePeriod = generateNewMembershipPeriod.execute(yesterdaysActivePeriod)
        }
        logger.info { "New period $currentActivePeriod has started, notifying all members of the previously active period." }
        membershipRepository.getByPeriod(yesterdaysActivePeriod)
            .forEach { membership -> notifyUser(membership.user, currentActivePeriod) }
    }

    private fun notifyUser(user: User, newPeriod: MembershipPeriod) {
        val params = mapOf(
            "member" to user.firstName,
            "price" to newPeriod.price,
            "periodName" to newPeriod.toString()
        )
        mailService.builder()
            .to(user.email)
            .subject(I18nUtil.i18n("new.membership.period"))
            .template("new-membership-period.html", params)
            .send()
    }
}