package be.sgl.backend.service.user.sync

enum class SyncState {
    HAS_EXTERNAL_OPEN_REGISTRATION,
    HAS_NEW_EXTERNAL_MEMBER_ID,
    HAS_EXTERNAL_MEMBER_ID_BUT_NO_ACCOUNT,
    HAS_UNMATCHED_EXTERNAL_FUNCTIONS,
    HAS_NO_ACTIVE_MEMBERSHIP,
    OK
}