name: Generate SBOM

on:
  push:
    branches:
      - feature/workshopWorkflows

jobs:
  build-sbom:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build JAR file
        run: mvn clean package -Dmaven.test.skip

      - uses: anchore/sbom-action@v0
        with:
          path: ./
          artifact-name: sbom2.json
          output-file: .

      - name: curl
        run: |
          curl -X POST -H 'X-Api-Key: odt_j5TEn8Qe_oPIpMDxzR8kXFsI6s8GJt8vQtixB4NIY' -F 'project=86a2ee45-fcbe-4c28-ab39-34351b6cd960' -F 'bom=@sbom2.json' https://dependency.portasecura.com/api/v1/bom
