name: Build and publish image

on:
  push:
    branches:
      - rokeppen/testMavenPublish

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build and publish with Maven
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/prd' ]]; then
            ENV_TAG=latest
          else
            ENV_TAG=dev
          fi
          mvn clean package \
            -Ddocker.publishRegistry.username=rokeppen \
            -Ddocker.publishRegistry.password=${{ secrets.TEST_PWD }} \
            -Ddocker.publishRegistry.url=ghcr.io \
            -Dspring-boot.build-image.publish=true \
            -Dspring-boot.build-image.imageName=ghcr.io/sgl/site-backend:${ENV_TAG}